packages:
  - apps/*
  - packages/*

allowBuilds:
  "@astryxdesign/cli": true
  "@astryxdesign/core": true
  esbuild: true
  lightningcss: true

catalog:
  "@types/node": ^26.5.0
  vite-plus: 0.3.1
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  typescript: ^7.0.2
  zod: ^4.5.4
  "@stylexjs/stylex": ^0.19.0
  "@stylexjs/eslint-plugin": ^0.19.0
  "@stylexjs/unplugin": ^0.19.0
  tsx: ^4.23.13
  "@astryxdesign/core": 0.5.4
  "@astryxdesign/theme-neutral": 0.5.4
  "@astryxdesign/cli": 0.5.4
  vitest: 4.1.11
  "@vitest/coverage-v8": 4.1.11
  "@vitest/ui": 4.1.11
  "@t3-oss/env-core": ^0.13.11

catalogs:
  orpc:
    "@orpc/client": 2.0.0-beta.35
    "@orpc/contract": 2.0.0-beta.35
    "@orpc/server": 2.0.0-beta.35
    "@orpc/openapi": 2.0.0-beta.35

  test:
    "@vitest/coverage-v8": 4.1.11
    "@vitest/ui": 4.1.11

  react:
    react: ^19.2.8
    react-dom: ^19.2.8
    "@types/react": ^19.2.18
    "@types/react-dom": ^19.2.7
    "@vitejs/plugin-react": ^6.1.1

  tanstack:
    "@tanstack/react-devtools": ^0.10.12
    "@tanstack/react-router": ^1.170.33
    "@tanstack/react-router-devtools": ^1.167.1
    "@tanstack/devtools-vite": ^0.8.5
    "@tanstack/router-cli": ^1.167.34
    "@tanstack/router-plugin": ^1.168.36

catalogMode: prefer

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

minimumReleaseAgeStrict: false
minimumReleaseAgeExcludePrune: true
minimumReleaseAgeIgnoreMissingTime: true

minimumReleaseAgeExclude:
  - "@orpc/client@2.0.0-beta.35"
  - "@orpc/contract@2.0.0-beta.35"
  - "@orpc/server@2.0.0-beta.35"
  - "@orpc/shared@2.0.0-beta.35"
  - "@orpc/openapi@2.0.0-beta.35"
  - "@orpc/json-schema@2.0.0-beta.35"
